args<-commandArgs(TRUE)
if(length(args)>1L).libPaths(c(normalizePath(args[2],winslash="/"),file.path(normalizePath(args[1],winslash="/"),".library"),.libPaths()))
library(microbiomeengine)
eq<-function(x,y)stopifnot(isTRUE(all.equal(x,y,tolerance=1e-10,check.attributes=FALSE)))
fixture<-function(m) {
 p<-example_project();ids<-paste0("sample / ",seq_len(ncol(m)))
 dimnames(m)<-list(paste0("feature",seq_len(nrow(m))),ids)
 md<-data.frame(sample_id=ids,group=rep(c("A","B"),length.out=length(ids)),unit=ids,row.names=ids)
 p$experiment<-SummarizedExperiment::SummarizedExperiment(assays=list(relative=m),colData=md);p
}
m<-matrix(c(1,2,7,4,3,2,8,6,2,3,7,5,9,4,1,7,2,8,2,9,4,6,3,8),4,6)/100
p<-fixture(m);before<-serialize(p,NULL);s<-list(metric="aitchison")
b<-calculate_beta(p,s);stopifnot(b$status=="ready",identical(before,serialize(p,NULL)))
clr<-sweep(log(m),2,colMeans(log(m)))
eq(b$transformation$values,clr);eq(b$distance,stats::dist(t(clr)))
eq(b$distance,vegan::vegdist(t(m),method="aitchison"))
eq(calculate_beta(fixture(sweep(m,2,1:6,"*")),s)$distance,b$distance)
eq(calculate_beta(fixture(m*c(1,3,2,8)),s)$distance,b$distance)
zero<-m;zero[1,1]<-0;pz<-fixture(zero)
stopifnot(calculate_beta(pz,s)$status=="blocked")
sa<-list(metric="aitchison",zero_policy="add",pseudocount=.001)
ba<-calculate_beta(pz,sa);stopifnot(ba$status=="ready")
eq(ba$distance,vegan::vegdist(t(zero),method="aitchison",pseudocount=.001))
stopifnot(!isTRUE(all.equal(ba$distance,calculate_beta(fixture(zero*10),sa)$distance)))
sr<-list(metric="robust.aitchison",robust_rank=2L)
set.seed(411);rng<-.Random.seed;br<-calculate_beta(pz,sr)
stopifnot(br$status=="ready",identical(rng,.Random.seed))
eq(br$distance,vegan::vegdist(t(zero),method="robust.aitchison",ropt=2,niter=5,tol=1e-5))
eq(calculate_beta(p,sr)$distance,b$distance)
eq(calculate_beta(fixture(zero*3),sr)$distance,br$distance)
stopifnot(identical(br$transformation,calculate_beta(pz,sr)$transformation))
for(bad in list(list(metric="aitchison",pseudocount=1),list(metric="aitchison",source="clr"),list(metric="aitchison",units="percentage"),list(metric="aitchison",correction="lingoes"),list(metric="robust.aitchison",pseudocount=1),list(metric="robust.aitchison",robust_rank=0),list(metric="robust.aitchison",robust_niter=1),list(metric="robust.aitchison",robust_tol=0)))stopifnot(calculate_beta(pz,bad)$status=="blocked")
for(v in c(-1,Inf,NaN)){bad<-m;bad[1,1]<-v;stopifnot(calculate_beta(fixture(bad),s)$status=="blocked")}
bad<-m;bad[,1]<-0;stopifnot(calculate_beta(fixture(bad),sa)$status=="blocked",calculate_beta(fixture(bad),sr)$status=="blocked")
bad<-zero;bad[1,]<-0;stopifnot(calculate_beta(fixture(bad),sr)$status=="blocked")
stopifnot(calculate_beta(fixture(m[1,,drop=FALSE]),s)$status=="blocked")
identical_data<-fixture(matrix(.1,4,6));bi<-calculate_beta(identical_data,s)
stopifnot(bi$status=="ready",bi$ordination$status=="undefined")
eq(calculate_beta(p)$distance,vegan::vegdist(t(m),method="bray"))
cat("PASS ordinary hand/public CLR, scaling/perturbation, addition sensitivity, robust public completion/RNG/repeatability, invalid inputs and preserved Bray\n")
stopifnot(br$transformation$optimizer$status=="iteration_limit",length(br$transformation$warnings)>0)
converged<-calculate_beta(pz,modifyList(sr,list(robust_tol=100)))
stopifnot(converged$transformation$optimizer$status=="converged",converged$transformation$optimizer$iterations==1)
stopifnot(calculate_beta(p,sr)$transformation$optimizer$status=="not_needed")
stopifnot(calculate_beta(fixture(zero[1:2,,drop=FALSE]),list(metric="robust.aitchison"))$status=="blocked")
degenerate<-matrix(.1,4,6);degenerate[1,1]<-0
stopifnot(calculate_beta(fixture(degenerate),sr)$status=="blocked")
for(bad in list(list(robust_rank=1001),list(robust_niter=1001),list(robust_rank=1.5),list(robust_tol=Inf)))stopifnot(calculate_beta(pz,modifyList(sr,bad))$status=="blocked")
ix<-c(6,2,4,1,5,3);reordered<-calculate_beta(fixture(m[,ix]),s)
eq(as.matrix(reordered$distance),as.matrix(b$distance)[ix,ix])
cs<-list(group="group",unit="unit",verified=TRUE,assignment="independent_units",evidence="Synthetic independent units",permutations=list(budget=19,seed=411,mode="sampled"))
for(recipe in list(s,sa,sr)) {
 q<-fixture(if(recipe$metric=="aitchison"&&is.null(recipe$pseudocount))m else zero)
 bb<-calculate_beta(q,recipe);cc<-compare_beta(bb,cs);stopifnot(cc$status=="ready")
 D<-bb$distance;raw<-t(SummarizedExperiment::assay(q$experiment,"relative"));md<-bb$metadata;perm<-cc$results$omnibus$permutation$indices
 ref<-if(recipe$metric=="robust.aitchison")vegan::adonis2(raw~group,data=md,method="robust.aitchison",ropt=2,niter=5,tol=1e-5,permutations=perm) else vegan::adonis2(raw~group,data=md,method="aitchison",pseudocount=if(is.null(recipe$pseudocount))0 else recipe$pseudocount,permutations=perm)
 saved<-vegan::adonis2(D~group,data=md,permutations=perm)
 eq(ref$F,saved$F);eq(ref$`Pr(>F)`,saved$`Pr(>F)`);eq(cc$tests$F,ref$F[1]);eq(cc$tests$p_raw,ref$`Pr(>F)`[1])
 eq(cc$results$omnibus$distance,D)
 dd<-beta_dispersion(bb,cs);stopifnot(dd$status=="ready")
 fit<-vegan::betadisper(D,factor(md$group),type="median",bias.adjust=FALSE)
 eq(dd$distances$distance,fit$distances)
 dp<-vegan::permutest(fit,permutations=dd$permutation$indices,parallel=1)
 eq(dd$tests$F,dp$tab$F[1]);eq(dd$tests$p_raw,dp$tab$`Pr(>F)`[1])
 family<-compare_beta(bb,modifyList(cs,list(pairs=list(c("A","B"),c("A","absent")))))
 stopifnot(family$status=="partial",is.na(family$pairwise$p_raw[2]))
 # The conditional and within-unit routes must consume the same distance.
 bb$metadata$cov<-c(1,3,2,6,4,8);bb$metadata_types["cov"]<-"continuous"
 conditional<-compare_beta(bb,modifyList(cs,list(route="conditional",covariates="cov")))
 stopifnot(conditional$status=="ready");eq(conditional$results$omnibus$distance,D)
 bb$metadata$unit<-rep(paste0("u",1:3),each=2)
 ps<-modifyList(cs,list(route="paired",assignment="independent_subjects",exchangeable=TRUE))
 paired<-compare_beta(bb,ps);within<-compare_beta(bb,modifyList(ps,list(route="within")))
 stopifnot(paired$status=="ready",within$status=="ready");eq(paired$results$omnibus$distance,D);eq(within$results$omnibus$distance,D)
 stopifnot(compare_beta(bb,modifyList(ps,list(ordered_time=TRUE)))$status=="blocked")
 q8<-fixture(cbind(m,m[,1:2]+.001));bt<-calculate_beta(q8,recipe)
 bt$metadata$unit<-rep(paste0("u",1:4),each=2);bt$metadata$visit<-rep(c("v1","v2"),4);bt$metadata$group<-rep(c("A","A","B","B"),each=2)
 bt$metadata_types["visit"]<-"categorical"
 trajectory<-compare_beta(bt,modifyList(ps,list(route="trajectory",visit="visit")))
 stopifnot(trajectory$status=="ready");dm<-as.matrix(bt$distance)
 eq(trajectory$results$omnibus$distance,as.dist(sqrt((dm[c(1,3,5,7),c(1,3,5,7)]^2+dm[c(2,4,6,8),c(2,4,6,8)]^2)/2)))
}
cat("PASS matrix-method versus saved-distance adonis2 with identical legal permutations, dispersion references, conditional/paired/within/family/trajectory distance propagation and guards\n")
root<-Sys.getenv("AITCHISON_EVIDENCE",tempdir());dir.create(root,recursive=TRUE,showWarnings=FALSE)
out<-tempfile("aitchison-",tmpdir=root);dir.create(out)
ids<-paste0("full ID / ",1:8)
mm<-matrix((seq_len(40)*7%%31)+1,5,8);mm[1,1]<-0;mm<-sweep(mm,2,colSums(mm),"/")*80
colnames(mm)<-ids
tab<-data.frame(clade_name=c("UNCLASSIFIED",paste0("k__Bacteria|s__taxon",1:5)),rbind(rep(10,8),mm),check.names=FALSE)
meta<-data.frame(sample_id=ids,group=rep(c("A","B"),each=4),unit=paste0("u",1:8),age=c(20,24,21,28,23,30,29,27))
utils::write.table(tab,file.path(out,"abundance.tsv"),sep="\t",quote=FALSE,row.names=FALSE)
utils::write.csv(meta,file.path(out,"metadata.csv"),row.names=FALSE)
x<-import_metaphlan(file.path(out,"abundance.tsv"),file.path(out,"metadata.csv"))
original<-prepare_project(x,list(rank="s",scale="percentage",denominator_kind="including_unclassified",coverage="removed",pipeline="Synthetic Aitchison fixture",database="synthetic",filtering="10 percent omitted",unclassified="supplied"),list(types=c(sample_id="id",group="categorical",unit="id",age="continuous")))
stopifnot(original$preparation$status=="ready")
rscript<-file.path(R.home("bin"),if(.Platform$OS.type=="windows")"Rscript.exe" else "Rscript")
for(recipe in list(sa,sr)) {
 q<-apply_beta(original,recipe,list(colour="group",shape="group"),comparison=cs,dispersion=cs)
 stopifnot(q$beta$status=="ready",q$beta$comparison$status=="ready",q$beta$dispersion$status=="ready")
 plot<-plot_beta(q);stopifnot(grepl("Aitchison",plot$labels$title),identical(attr(plot,"beta_data")$sample_id,ids))
 directory<-file.path(out,recipe$metric);export_beta(q,directory)
 eq(as.matrix(read.delim(file.path(directory,"transformed-values.tsv"),check.names=FALSE)[,-1]),q$beta$transformation$values)
 stopifnot(identical(open_project(file.path(directory,"project.rds"))$beta,q$beta))
 code<-system2(rscript,c("--vanilla",shQuote(file.path(directory,"replay.R")),shQuote(directory),shQuote(paste0(directory,"-fresh"))),stdout=paste0(directory,"-fresh.log"),stderr=paste0(directory,"-fresh-error.log"))
 stopifnot(code==0,file.exists(file.path(paste0(directory,"-fresh"),"VERIFIED")))
 combined<-paste0(directory,"-combined");export_project(q,combined)
 code<-system2(rscript,c("--vanilla",shQuote(file.path(combined,"replay.R")),shQuote(combined),shQuote(paste0(combined,"-fresh"))),stdout=paste0(combined,"-fresh.log"),stderr=paste0(combined,"-fresh-error.log"))
 stopifnot(code==0,file.exists(file.path(paste0(combined,"-fresh"),"VERIFIED")))
 switched<-apply_beta(q);stopifnot(is.null(switched$beta$comparison),is.null(switched$beta$dispersion),is.null(switched$beta$transformation))
 stale<-apply_preparation(q,list(samples=list(enabled=TRUE,ids=ids[1:6])));stopifnot(stale$beta$status=="stale")
}
if(nzchar(Sys.getenv("AITCHISON_EVIDENCE")))save_project(original,file.path(root,"review-project.rds"))
cat("PASS exact transformed exports, source-backed save/reopen, both clean-process standalone/combined replays, metric switching and staleness\n")
cat("AITCHISON_EVIDENCE_ROOT",normalizePath(out,winslash="/"),"\n")
