args<-commandArgs(TRUE)
if(length(args)>1L).libPaths(c(normalizePath(args[2],winslash="/"),file.path(normalizePath(args[1],winslash="/"),".library"),.libPaths()))
library(microbiomeengine)
p<-example_project();m<-SummarizedExperiment::assay(p$experiment,"relative")
fails<-function(expr)stopifnot(inherits(tryCatch({force(expr);NULL},error=function(e)e),"error"))
near<-function(a,b)stopifnot(isTRUE(all.equal(as.vector(a),as.vector(b),tolerance=1e-12)))
h<-apply_assay(p,list(name="H",method="hellinger"))
near(h$assay_layers$H$values,sqrt(sweep(m,2,colSums(m),"/")))
stopifnot(identical(h$input,p$input),identical(h$canonical,p$canonical),identical(h$experiment,p$experiment),identical(h$mass,p$mass))
z<-apply_assay(h,list(name="C",method="clr",zero_policy="add",pseudocount=.001))
near(z$assay_layers$C$values,sweep(log(m+.001),2,colMeans(log(m+.001)),"-"))
l<-apply_assay(z,list(name="L",method="log",zero_policy="add",pseudocount=.001))
near(l$assay_layers$L$values,log(m+.001))
percent<-apply_assay(p,list(name="C",method="clr",units="percentage",zero_policy="add",pseudocount=.1))
near(percent$assay_layers$C$values,z$assay_layers$C$values)
lp<-apply_assay(p,list(name="LP",method="log",units="percentage",zero_policy="add",pseudocount=.1))
near(lp$assay_layers$LP$values,l$assay_layers$L$values+log(100))
different<-apply_assay(p,list(name="D",method="clr",zero_policy="add",pseudocount=.5))
stopifnot(!isTRUE(all.equal(different$assay_layers$D$values,z$assay_layers$C$values)))
ref<-mia::transformAssay(p$experiment,assay.type="relative",method="hellinger",MARGIN="samples",name="reference",pseudocount=0)
near(SummarizedExperiment::assay(ref,"reference"),h$assay_layers$H$values)
fails(apply_assay(h,list(name="H")));fails(apply_assay(h,list(name="relative")))
fails(apply_assay(l,list(name="signed",source="C",method="hellinger")))
chain<-apply_assay(h,list(name="HL",source="H",units="derived",method="log",zero_policy="add",pseudocount=.01))
near(chain$assay_layers$HL$values,log(h$assay_layers$H$values+.01))
for(bad in c(-1,NA,Inf)) {q<-p;SummarizedExperiment::assay(q$experiment,"relative")[1,1]<-bad;fails(apply_assay(q,list(name="bad")))}
q<-p;SummarizedExperiment::assay(q$experiment,"relative")[,1]<-0
fails(apply_assay(q,list(name="bad")));fails(apply_assay(q,list(name="bad",method="clr")))
qzero<-apply_assay(q,list(name="zero",method="clr",zero_policy="add",pseudocount=.01));near(qzero$assay_layers$zero$values[,1],rep(0,nrow(m)))
for(pc in list(TRUE,NA_real_,Inf,-1))fails(apply_assay(p,list(name="invalid",method="log",zero_policy="add",pseudocount=pc)))
qmeta<-p;rownames(SummarizedExperiment::colData(qmeta$experiment))<-rev(colnames(m));fails(microbiomeengine:::assays_current(microbiomeengine:::retain_assays(h,qmeta)))
qconst<-p;SummarizedExperiment::assay(qconst$experiment,"relative")[]<-.1
const<-apply_assay(qconst,list(name="constant",method="clr"));near(const$assay_layers$constant$values,rep(0,length(m)))
qclose<-p;SummarizedExperiment::assay(qclose$experiment,"relative")<-sweep(m,2,colSums(m),"/")
if(all(m>0)){rawclr<-apply_assay(p,list(name="rawclr",method="clr"));closedclr<-apply_assay(qclose,list(name="closedclr",method="clr"));near(rawclr$assay_layers$rawclr$values,closedclr$assay_layers$closedclr$values)}
est<-p;SummarizedExperiment::assay(est$experiment,"estimated_reads")<-m*123
estimated<-apply_assay(est,list(name="est",source="estimated_reads",units="estimated_reads"));near(estimated$assay_layers$est$values,h$assay_layers$H$values)
stopifnot(grepl("not observed counts",estimated$assay_layers$est$source_meaning))
q<-p;q$experiment<-q$experiment[1,,drop=FALSE];SummarizedExperiment::assay(q$experiment,"relative")[]<-.2
one<-apply_assay(q,list(name="one",method="clr"));near(one$assay_layers$one$values,rep(0,ncol(q$experiment)))
q$experiment<-q$experiment[FALSE,,drop=FALSE];fails(apply_assay(q,list(name="empty")))
pa<-apply_beta(apply_alpha(p));pa2<-apply_assay(pa,list(name="H"));stopifnot(identical(pa2$alpha,pa$alpha),identical(pa2$beta,pa$beta))
changed<-apply_preparation(chain,list(samples=list(enabled=TRUE,ids=colnames(m)[1:2])))
stopifnot(all(vapply(changed$assay_layers,function(x)x$status=="stale"&&is.null(x$values),logical(1))))
rebuilt<-rebuild_assays(changed);stopifnot(ncol(rebuilt$assay_layers$H$values)==2)
styled<-microbiomeengine:::retain_analysis(chain,prepare_project(p$input,p$declarations,p$design,modifyList(p$settings,list(palette="Dark 3")),p$preparation$settings))
stopifnot(identical(styled$assay_layers,chain$assay_layers))
ranked<-microbiomeengine:::retain_analysis(chain,prepare_project(p$input,modifyList(p$declarations,list(rank="g")),p$design,p$settings,p$preparation$settings))
stopifnot(ranked$assay_layers$H$status=="stale")
run<-tempfile("assay-tests-");dir.create(run)
save_project(l,file.path(run,"saved.rds"));stopifnot(identical(open_project(file.path(run,"saved.rds")),l))
export_assays(l,file.path(run,"bundle"));fails(export_assays(l,file.path(run,"bundle")))
for(n in names(l$assay_layers))stopifnot(identical(read.delim(file.path(run,"bundle",paste0("assay-",n,"-values.tsv")))$value,assay_values(l,n)$value))
replay_project(file.path(run,"bundle"),file.path(run,"replay"))
fails(export_assays(changed,file.path(run,"stale")));stopifnot(!file.exists(file.path(run,"stale","COMPLETE")))
cat("PASS assay references, units, domains, chains, immutability, staleness, diversity preservation and replay\n")
