args<-commandArgs(TRUE)
if(length(args)>1L).libPaths(c(normalizePath(args[2],winslash="/"),file.path(normalizePath(args[1],winslash="/"),".library"),.libPaths()))
library(microbiomeengine)
eq<-function(x,y,tol=1e-9)stopifnot(isTRUE(all.equal(x,y,tolerance=tol,check.attributes=FALSE)))
fails<-function(expr)stopifnot(inherits(try(force(expr),silent=TRUE),"try-error"))
p<-example_project();before<-serialize(p,NULL);b<-calculate_beta(p)
stopifnot(b$status=="ready",identical(before,serialize(p,NULL)))
m<-SummarizedExperiment::assay(p$experiment,"relative")
ref<-outer(seq_len(ncol(m)),seq_len(ncol(m)),Vectorize(function(i,j)sum(abs(m[,i]-m[,j]))/sum(m[,i]+m[,j])))
eq(as.matrix(b$distance),ref)
J<-diag(ncol(m))-1/ncol(m);G<--J%*%(ref^2)%*%J/2
eq(b$ordination$eigenvalues,eigen(G,symmetric=TRUE)$values[abs(eigen(G,symmetric=TRUE)$values)>1e-10])
z<-p;SummarizedExperiment::assay(z$experiment,"relative")[,1:2]<-cbind(c(.4,.1),c(.1,.1))
eq(as.matrix(calculate_beta(z)$distance)[1,2],3/7)
for(v in c(-1,Inf,NaN)){z<-p;SummarizedExperiment::assay(z$experiment,"relative")[1,1]<-v;stopifnot(calculate_beta(z)$status=="blocked")}
z<-p;SummarizedExperiment::assay(z$experiment,"relative")[,1]<-0;stopifnot(calculate_beta(z)$status=="blocked")
z<-p;SummarizedExperiment::assay(z$experiment,"relative")[]<-.2;b0<-calculate_beta(z);stopifnot(b0$status=="ready",b0$ordination$status=="undefined")
p<-apply_beta(p);display<-p;display$settings$top_n<-1L;eq(calculate_beta(p)$distance,calculate_beta(display)$distance)
p2<-apply_preparation(p,list(samples=list(enabled=TRUE,ids=c("S1","S2"))));stopifnot(p2$beta$status=="stale")
cat("PASS beta manual Bray, immutable mass/source, geometry, invalid and stale fixtures\n")
z<-example_project();mm<-.2*t(rbind(c(1,0,0),c(0,1,0),c(0,0,1),c(1,1,1)));dimnames(mm)<-list(paste0("feature",1:3),colnames(z$experiment))
z$experiment<-SummarizedExperiment::SummarizedExperiment(assays=list(relative=mm),colData=SummarizedExperiment::colData(z$experiment))
b<-calculate_beta(z);stopifnot(b$status=="ready",b$ordination$negative_inertia>0)
DD<-as.matrix(b$distance);J<-diag(4)-1/4;GG<--J%*%(DD^2)%*%J/2;positive<-as.matrix(b$ordination$scores[,-1]);negative<-b$ordination$negative_scores
eq(tcrossprod(positive)-tcrossprod(negative),GG)
bc<-calculate_beta(z,list(correction="lingoes"));stopifnot(bc$status=="ready",bc$ordination$constant>0);eq(bc$distance,b$distance)
eq(bc$ordination$distance,sqrt(b$distance^2+2*bc$ordination$constant));stopifnot(bc$ordination$negative_inertia<1e-9)
mm<-matrix(seq_len(601*4)%%17+1,601,4)/1e5;dimnames(mm)<-list(paste0("feature",1:601),colnames(z$experiment));z$experiment<-SummarizedExperiment::SummarizedExperiment(assays=list(relative=mm),colData=SummarizedExperiment::colData(z$experiment));big<-calculate_beta(z)
stopifnot(big$status=="ready",length(big$features)==601);eq(as.matrix(big$distance)[1,2],sum(abs(mm[,1]-mm[,2]))/sum(mm[,1]+mm[,2]))
cat("PASS negative-eigenvalue signed reconstruction, distinct Lingoes geometry and all601 analytical features\n")
