args<-commandArgs(TRUE)
if(length(args)>1L).libPaths(c(normalizePath(args[2],winslash="/"),file.path(normalizePath(args[1],winslash="/"),".library"),.libPaths()))
library(microbiomeengine)
eq<-function(x,y,tol=1e-9)stopifnot(isTRUE(all.equal(x,y,tolerance=tol,check.attributes=FALSE)))
fails<-function(expr)stopifnot(inherits(try(force(expr),silent=TRUE),"try-error"))
root<-Sys.getenv("BETA_EVIDENCE",tempdir());dir.create(root,recursive=TRUE,showWarnings=FALSE);out<-tempfile("beta-validation-",tmpdir=root);dir.create(out)
ids<-paste0("full ID / ",1:12);group<-rep(c("A","B","C"),each=4)
m<-rbind(seq(10,40,length.out=12),c(25,22,24,26,20,15,21,19,12,16,17,13),c(15,18,11,16,13,20,12,14,18,11,12,15));m<-rbind(m,80-colSums(m));colnames(m)<-ids
tab<-data.frame(clade_name=c("UNCLASSIFIED",paste0("k__Bacteria|s__taxon",1:4)),rbind(rep(10,12),m),check.names=FALSE)
meta<-data.frame(sample_id=ids,group=group,unit=paste0("unit",1:12),age=c(20,24,21,28,23,30,29,27,32,31,35,34),symbol=rep(c("circle","square",NA,"<Missing>"),3),panel=rep(c("P","Q"),6))
utils::write.table(tab,file.path(out,"abundance.tsv"),sep="\t",row.names=FALSE,quote=FALSE);utils::write.csv(meta,file.path(out,"metadata.csv"),row.names=FALSE,na="")
x<-import_metaphlan(file.path(out,"abundance.tsv"),file.path(out,"metadata.csv"))
p<-prepare_project(x,list(rank="s",scale="percentage",denominator_kind="including_unclassified",coverage="removed",pipeline="Synthetic beta fixture",database="synthetic",filtering="10 percent omitted",unclassified="supplied"),list(types=c(sample_id="id",group="categorical",unit="id",age="continuous",symbol="categorical",panel="categorical")))
stopifnot(p$preparation$status=="ready")
s<-list(group="group",unit="unit",verified=TRUE,assignment="independent_units",evidence="Synthetic independent assignment",permutations=list(budget=29,seed=3604,mode="sampled"),pairs=list(c("A","B"),c("A","C")))
ds<-s;ds$pairs<-list();style<-list(group="group",facet="panel",colour="group",shape="symbol",colours=c(A="#8B0066",B="#167A42",C="#2458BC"),group_centres=TRUE)
p<-apply_beta(p,plot_settings=style,comparison=s,dispersion=ds);if(p$beta$comparison$status!="ready")print(p$beta$comparison);stopifnot(p$beta$status=="ready",p$beta$comparison$status=="ready",p$beta$dispersion$status=="ready")
saved<-serialize(p$beta[c("distance","ordination","comparison","dispersion")],NULL);plot<-plot_beta(p);d<-attr(plot,"beta_data");stopifnot(identical(d$sample_id,ids),nlevels(d$.shape)==4)
built<-ggplot2::ggplot_build(plot)$data[[1]];eq(sort(built$x),sort(d$.x));eq(sort(built$y),sort(d$.y));stopifnot(setequal(built$colour,unname(style$colours)))
p$beta$plot_settings<-microbiomeengine:::beta_plot_settings(modifyList(style,list(colour="age",colour_type="continuous",colours=character(),fixed_shape=17L)))
plot2<-plot_beta(p);stopifnot(is.numeric(attr(plot2,"beta_data")$.colour),identical(saved,serialize(p$beta[c("distance","ordination","comparison","dispersion")],NULL)))
fails(plot_beta(p,modifyList(style,list(shape="age"))));fails(plot_beta(p,modifyList(style,list(fixed_colour="not-a-colour"))));fails(plot_beta(p,modifyList(style,list(shapes=c(circle=99)))))
p$beta$plot_settings<-microbiomeengine:::beta_plot_settings(style)
save_project(p,file.path(out,"saved.rds"));q<-open_project(file.path(out,"saved.rds"));eq(p$beta,q$beta)
bundle<-file.path(out,"bundle");export_beta(p,bundle);stopifnot(file.exists(file.path(bundle,"COMPLETE")),file.exists(file.path(bundle,"beta.html")),file.exists(file.path(bundle,"omnibus-permutation-indices.tsv")))
plotdata<-read.delim(file.path(bundle,"ordination-plot-data.tsv"),check.names=FALSE);eq(plotdata$.x,d$.x);eq(plotdata$.y,d$.y);stopifnot(identical(plotdata$sample_id,ids))
fails(export_beta(p,bundle));replay_beta(bundle,file.path(out,"replayed"))
rscript<-file.path(R.home("bin"),"Rscript.exe");if(!file.exists(rscript))rscript<-file.path(R.home("bin"),"Rscript")
code<-system2(rscript,c("--vanilla",shQuote(file.path(bundle,"replay.R")),shQuote(bundle),shQuote(file.path(out,"fresh"))),stdout=file.path(out,"fresh.log"),stderr=file.path(out,"fresh-error.log"));stopifnot(code==0,file.exists(file.path(out,"fresh","VERIFIED")))
for(fmt in c("pdf",if(requireNamespace("svglite",quietly=TRUE))"svg")){fig<-file.path(out,paste0("styled.",fmt));microbiomeengine:::alpha_write_figure(plot,fig,list(format=fmt,width=10,height=7));stopifnot(file.info(fig)$size>0)}
blocked<-p;blocked$beta$comparison<-compare_beta(blocked$beta,modifyList(s,list(verified=FALSE)));stopifnot(blocked$beta$comparison$status=="blocked");export_beta(blocked,file.path(out,"blocked"));replay_beta(file.path(out,"blocked"),file.path(out,"blocked-replay"))
full<-apply_alpha(p);export_project(full,file.path(out,"combined"));replay_project(file.path(out,"combined"),file.path(out,"combined-replay"))
writeLines("tamper",file.path(bundle,"inputs","metadata.txt"));fails(replay_beta(bundle,file.path(out,"tampered-replay")))
cat("PASS styled geometry/IDs, independent mappings, invalid styles, no refit, PNG/PDF/SVG, collision, save/reopen, blocked/full/fresh replay and tamper rejection\n")
cat("BETA_EVIDENCE_ROOT",normalizePath(out,winslash="/"),"\n")
if(nzchar(Sys.getenv("BETA_EVIDENCE")))saveRDS(p,file.path(root,"review-project.rds"))
