library(microbiomeengine)
local({
  original <- .libPaths()
  on.exit(.libPaths(original), add=TRUE)
  work <- tempfile("replay-library-"); dir.create(work)
  historical <- file.path(work,"historical-library"); dir.create(historical)
  p <- apply_beta(apply_alpha(example_project()), list(metric="aitchison"))
  stopifnot(p$alpha$status=="ready", p$beta$status=="ready")
  for (kind in c("project","alpha","beta")) {
    bundle <- file.path(work,paste0(kind,"-bundle"))
    output <- file.path(work,paste0(kind,"-replayed"))
    .libPaths(c(historical,original))
    switch(kind,project=export_project(p,bundle),alpha=export_alpha(p,bundle),beta=export_beta(p,bundle))
    .libPaths(original)
    env <- new.env(parent=globalenv())
    env$commandArgs <- function(trailingOnly=FALSE) c(bundle,output)
    source(file.path(bundle,"replay.R"),local=env)
    stopifnot(identical(.libPaths(),original),file.exists(file.path(output,"VERIFIED")))
  }
  cat("PASS project/alpha/beta generated replays preserve active libraries despite existing historical paths\n")
})
