args<-commandArgs(TRUE)
if(length(args)>1L).libPaths(c(normalizePath(args[2],winslash="/"),file.path(normalizePath(args[1],winslash="/"),".library"),.libPaths()))
library(microbiomeengine)
ns<-asNamespace("microbiomeengine")
context<-get("diversity_input_context",ns);rank_apply<-get("diversity_apply_rank",ns)
p<-example_project()
stopifnot(grepl("No alpha result yet",as.character(context(p,"alpha")),fixed=TRUE))
stopifnot(grepl("Supplied relative abundance",as.character(context(p,"beta")),fixed=TRUE))
stopifnot(identical(rank_apply(p,"s"),p))
stopifnot(inherits(try(rank_apply(p,"p"),silent=TRUE),"try-error"))
p<-apply_alpha(p,list(metrics=c("shannon","gini_simpson")),list(group="group"))
p<-apply_beta(p)
p<-apply_assay(p,list(name="H",method="hellinger"))
original<-p
for(rank in c("g","k","s")) {
 q<-rank_apply(p,rank)
 ref<-prepare_project(p$input,modifyList(p$declarations,list(rank=rank)),p$design,p$settings,p$preparation$settings)
 stopifnot(identical(q$experiment,ref$experiment),identical(q$mass,ref$mass),identical(q$input,p$input),identical(q$settings,p$settings))
 stopifnot(q$alpha$status=="stale",q$beta$status=="stale",q$assay_layers$H$status=="stale",is.null(q$assay_layers$H$values))
 stopifnot(identical(q$alpha$values,p$alpha$values),identical(q$beta$distance,p$beta$distance),identical(q$alpha$plot_settings,p$alpha$plot_settings))
 p<-q
}
p<-rebuild_assays(apply_beta(apply_alpha(p,original$alpha$settings,original$alpha$plot_settings)))
stopifnot(identical(p$alpha$values,original$alpha$values),identical(p$beta$distance,original$beta$distance),identical(p$assay_layers,original$assay_layers))
run<-tempfile("polish-");dir.create(run);save_project(p,file.path(run,"saved.rds"));stopifnot(identical(open_project(file.path(run,"saved.rds")),p))
# Paired and estimate-only semantics, with unchanged numeric algorithms.
root<-system.file("extdata",package="microbiomeengine")
x<-import_metaphlan(NULL,file.path(root,"metadata.csv"),estimates=file.path(root,"estimated-reads.tsv"))
ep<-prepare_project(x,modifyList(example_project()$declarations,list(estimate_unit="estimated_reads",estimate_normalization=TRUE)),example_project()$design)
stopifnot(grepl("Relative estimated-read contribution",as.character(context(ep,"alpha")),fixed=TRUE))
ep<-apply_alpha(ep,list(source="estimated_reads",metrics="shannon"))
stopifnot(grepl("Units: estimated reads",as.character(context(ep,"alpha")),fixed=TRUE))
# Actual Shiny handlers: first use, draft rank, invalid/recovery, resource policy and no refits.
seeded<-get("app_server",ns)
environment(seeded)<-list2env(list(seed_project=example_project()),parent=environment(seeded));formals(seeded)$project<-quote(seed_project)
shiny::testServer(seeded,{
 stopifnot(grepl("No alpha result yet",output$alpha_pending))
 stopifnot(!grepl("Error",output$alpha_style_controls$html))
 stopifnot(grepl("Preview or apply",output$beta_plan_selector$html))
 session$setInputs(alpha_source="relative",alpha_metrics="shannon",alpha_apply=1)
 before<-state()$alpha
 session$setInputs(alpha_rank="g")
 stopifnot(state()$declarations$rank=="s",grepl("pending",output$alpha_rank_pending),inherits(try(alpha_guard(),silent=TRUE),"try-error"))
 session$setInputs(alpha_apply=2)
 stopifnot(identical(state()$alpha,before),grepl("pending shared rank",status()))
 session$setInputs(alpha_rank_apply=1)
 stopifnot(state()$declarations$rank=="g",state()$alpha$status=="stale",grepl("stale",output$alpha_pending))
 stopifnot(grepl("Species",output$alpha_input_context$html),grepl("Genus",output$alpha_input_context$html))
 session$setInputs(alpha_apply=3)
 stopifnot(state()$alpha$rank=="g")
 session$setInputs(beta_rank="s",beta_rank_apply=1)
 session$setInputs(alpha_rank="s")
 stopifnot(state()$declarations$rank=="s")
 session$setInputs(beta_max_samples=2,beta_apply=1)
 stopifnot(state()$beta$status=="blocked",ncol(state()$experiment)==4L,grepl("without dropping",output$beta_cohort_budget))
 session$setInputs(beta_max_samples=4,beta_apply=2)
 stopifnot(state()$beta$status=="ready",identical(attr(state()$beta$distance,"Labels"),colnames(state()$experiment)))
 d<-state()$beta$distance;o<-state()$beta$ordination
 session$setInputs(beta_fixed_colour="#336699",beta_style_apply=1)
 stopifnot(identical(d,state()$beta$distance),identical(o,state()$beta$ordination))
 session$setInputs(beta_rank="p",beta_rank_apply=2)
 stopifnot(state()$declarations$rank=="s",grepl("supplied terminal rank",status()))
 session$setInputs(beta_rank="s",beta_rank_apply=3)
 session$setInputs(alpha_apply=4)
 a<-state()$alpha$values
 session$setInputs(alpha_cmp_method="welch",alpha_cmp_group="group",alpha_cmp_reference="A",alpha_cmp_unit="unit",alpha_cmp_assignment="independent_units",alpha_cmp_verified=TRUE,alpha_cmp_evidence="Synthetic independent fixture",alpha_compare=1)
 fit<-state()$alpha$comparison
 session$setInputs(alpha_fixed_colour="#884422",alpha_style_apply=1)
 stopifnot(identical(a,state()$alpha$values),identical(fit,state()$alpha$comparison))
})
stopifnot(microbiomeengine:::beta_settings()$max_samples==500L)
for(bad in c(1,2001,2.5))stopifnot(inherits(try(microbiomeengine:::beta_settings(list(max_samples=bad)),silent=TRUE),"try-error"))
# Fingerprint policy deliberately unchanged; no lifecycle refactor hidden in UI work.
bp<-example_project()
stopifnot(!identical(microbiomeengine:::beta_parent(bp,microbiomeengine:::beta_settings(list(max_samples=4)))$fingerprint,microbiomeengine:::beta_parent(bp,microbiomeengine:::beta_settings(list(max_samples=5)))$fingerprint))
cat("PASS UI context, first use, source meaning, rank identity/invalidation/recovery, styles/no-refit, unchanged safety policy and saved state\n")
